document.getElementById('tableid').innerHTML=
`<table>
    <tr>
        <th>Name</th>
        <th>Age</th>
        <th>Address</th>
        <th>DOB</th>
        <th>Email</th>
        <th>Gender</th>
    </tr>
    <tr>
        <td>Jhon</td>
        <td>22</td>
        <td>Bengaluru</td>
        <td>22/07/1997</td>
        <td>jhon1997@gmail.com</td>
        <td>M</td>
    </tr>
    <tr>
        <td>Guldu</td>
        <td>20</td>
        <td>Chennai</td>
        <td>22/07/1999</td>
        <td>guldu1999@gmail.com</td>
        <td>M</td>
    </tr>
    <tr>
        <td>Sundar</td>
        <td>14</td>
        <td>Cuttack</td>
        <td>22/07/2005</td>
        <td>sundar2005@gmail.com</td>
        <td>M</td>
    </tr>
    <tr>
        <td>Dinga</td>
        <td>26</td>
        <td>Kolkata</td>
        <td>22/07/1993</td>
        <td>dinga1993@gmail.com</td>
        <td>M</td>
    </tr>
</table>`;